### ISSUE TITLE
assert_error hangs when the passed function does not raise errors

### ISSUE THREAD

**Issue by nrk** [norman/telescope#1]
When using assert_error to test a function that does not raise any error, telescope gets stuck on that test with the CPU at 100% until the user intervenes with CTRL+C, then the rest of the tests are processed (tested with Lua 5.1.4).

See the following gist http://gist.github.com/418929 for reproduction code and the respective output.

**Comment by norman** [comment]
OMG a bug report for Telescope! I'll take a look into this as soon as possible. I'll be doing some travelling so it might not be until early next week though.

**Comment by nrk** [comment]
No worries it's not a blocking issue, after all if I have an assert_error in my tests it's better to get the error raised or it would mean that I have a problem in my library that's better to fix :-) Thanks!

**Comment by norman** [comment]
This is now fixed in master.

**Comment by nrk** [comment]
It works fine now, thanks.
