### ISSUE TITLE
Lua 5.2 compatibility (removal of setfenv and getfenv)?

### ISSUE THREAD

**Issue by cymen** [norman/telescope#18]
Are there any plans for making telescope compatible with Lua 5.2 which removes setfenv and getfenv?

**Comment by norman** [comment]
The master branch currently supports 5.2 through David Manura's compat_env, but it hasn't been pushed to Luarocks yet.

I'm also experimenting with a version with that makes much better use of environments and doesn't use an emulated getfenv/setfenv on 5.2, but I don't have anything to push or announce yet.

**Comment by cymen** [comment]
Ah! I was using master then tried Luarocks (along with some other tinkering) and wondered where I went wrong. Now it all makes sense. Thanks you. I'll stick with master.

**Comment by hinell** [comment]
Neovim depends on the LuaJIT 2.1, the latter supports Lua 5.2 features only partially. See for more info: https://blast.hk/moonloader/luajit/changes.html
