### ISSUE TITLE
Making telescope use LuaJIT to run specs

### ISSUE THREAD

**Issue by dolzenko** [norman/telescope#20]
I would like to know if there is an easy way to make telescope use LuaJIT when running specs/or if there is any 'best practice' to do so?

**Comment by pflaquerre** [comment]
Telescope itself is written in lua, so all you have to do is explicitly use luajit: `luajit tsc my_spec.lua`.

Alternatively, you can change the first line of tsc `#!/usr/bin/env lua` to `#!/usr/bin/env luajit`, assuming luajit is on your `PATH`.

**Comment by dolzenko** [comment]
Thanks, makes sense!

And big props for the software itself!
