### ISSUE TITLE
Global "t2" ?

### ISSUE THREAD

**Issue by Yonaba** [norman/telescope#23]
Hi,

In [telescope.lua](https://github.com/norman/telescope/blob/master/telescope.lua), the private function `invert_table` creates a global table named `t2` at [line 183](https://github.com/norman/telescope/blob/master/telescope.lua#L183).
Shouldn't it be local to the function, or is it intended ?

Regards,
Roland.

**Comment by norman** [comment]
That's a bug! Completely, totally unintentional.

**Comment by norman** [comment]
Fixed in c80b928e306cad7195e1ce5b92ddcdcb0a2c50b2. Thanks!
